# Generated by Django 2.0.7 on 2018-07-27 12:20

import SearchPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('clinicid', models.CharField(max_length=30, unique=True)),
                ('admdate', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('marital', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=30)),
                ('contrac', models.CharField(choices=[('None', 'None'), ('IUD', 'IUD'), ('Pills', 'Pills')], default='None', max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('tel', models.CharField(blank=True, max_length=30, unique=True, validators=[SearchPage.models.validate_nostr])),
                ('socialid', models.CharField(max_length=14, unique=True, validators=[SearchPage.models.validate_14, SearchPage.models.validate_nostr])),
            ],
        ),
    ]
