# Generated by Django 2.1 on 2018-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchPage', '0004_auto_20180808_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True)),
                ('onset', models.CharField(blank=True, choices=[('gradual', 'gradual'), ('sudden', 'sudden')], max_length=30)),
                ('course', models.CharField(blank=True, choices=[('progressive', 'Progressive'), ('regressive', 'Regressive'), ('stationary', 'Stationary'), ('RE', 'Remissions and Exacerbations')], max_length=30)),
                ('duration', models.IntegerField(blank=True)),
                ('scalp', models.TextField(blank=True)),
                ('distribution', models.CharField(blank=True, choices=[('diffuse', 'Diffuse'), ('frontal', 'Frontal'), ('temporal', 'Temporal'), ('occipital', 'Occipital'), ('vertical', 'Vertical')], max_length=30)),
                ('hairpull', models.CharField(choices=[('+ve', 'Positive'), ('-ve', 'Negative'), ('None', 'Not done')], default='None', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='aalopecia',
            name='sinlair',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='AA',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='atopy',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='familyAA',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='nails',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='salt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='sites',
            field=models.CharField(max_length=150),
        ),
    ]
