# Generated by Django 2.1 on 2018-08-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SearchPage', '0005_auto_20180808_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairloss',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SearchPage.Patients'),
        ),
    ]
