# Generated by Django 2.1 on 2018-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchPage', '0006_hairloss_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aalopecia',
            name='pattern',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aalopecia',
            name='sinlair',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='Type',
            field=models.CharField(blank=True, choices=[('S', 'Single patch'), ('M', 'Multiple patches'), ('AT', 'Alopecia Totalis'), ('AU', 'Alopecia Universalis'), ('D', 'Diffuse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='salt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aareata',
            name='sites',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
